// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/hello.proto

package proto;

public final class Hello {
  private Hello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      id_ = 0L;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Hello.internal_static_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Hello.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Hello.Request.class, proto.Hello.Request.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Hello.Request)) {
        return super.equals(obj);
      }
      proto.Hello.Request other = (proto.Hello.Request) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Hello.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Hello.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Hello.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Hello.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Hello.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Hello.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Hello.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Hello.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Hello.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Hello.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Hello.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Hello.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Hello.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        proto.Hello.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Hello.internal_static_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Hello.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Hello.Request.class, proto.Hello.Request.Builder.class);
      }

      // Construct using proto.Hello.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Hello.internal_static_Request_descriptor;
      }

      public proto.Hello.Request getDefaultInstanceForType() {
        return proto.Hello.Request.getDefaultInstance();
      }

      public proto.Hello.Request build() {
        proto.Hello.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.Hello.Request buildPartial() {
        proto.Hello.Request result = new proto.Hello.Request(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Hello.Request) {
          return mergeFrom((proto.Hello.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Hello.Request other) {
        if (other == proto.Hello.Request.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Hello.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Hello.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Request)
    }

    // @@protoc_insertion_point(class_scope:Request)
    private static final proto.Hello.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Hello.Request();
    }

    public static proto.Hello.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public proto.Hello.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      id_ = 0L;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Hello.internal_static_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Hello.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Hello.Response.class, proto.Hello.Response.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Hello.Response)) {
        return super.equals(obj);
      }
      proto.Hello.Response other = (proto.Hello.Response) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Hello.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Hello.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Hello.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Hello.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Hello.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Hello.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Hello.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Hello.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Hello.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Hello.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Hello.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Hello.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Hello.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        proto.Hello.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Hello.internal_static_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Hello.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Hello.Response.class, proto.Hello.Response.Builder.class);
      }

      // Construct using proto.Hello.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Hello.internal_static_Response_descriptor;
      }

      public proto.Hello.Response getDefaultInstanceForType() {
        return proto.Hello.Response.getDefaultInstance();
      }

      public proto.Hello.Response build() {
        proto.Hello.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.Hello.Response buildPartial() {
        proto.Hello.Response result = new proto.Hello.Response(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Hello.Response) {
          return mergeFrom((proto.Hello.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Hello.Response other) {
        if (other == proto.Hello.Response.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Hello.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Hello.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final proto.Hello.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Hello.Response();
    }

    public static proto.Hello.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public proto.Hello.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Request requestList = 1;</code>
     */
    java.util.List<proto.Hello.Request> 
        getRequestListList();
    /**
     * <code>repeated .Request requestList = 1;</code>
     */
    proto.Hello.Request getRequestList(int index);
    /**
     * <code>repeated .Request requestList = 1;</code>
     */
    int getRequestListCount();
    /**
     * <code>repeated .Request requestList = 1;</code>
     */
    java.util.List<? extends proto.Hello.RequestOrBuilder> 
        getRequestListOrBuilderList();
    /**
     * <code>repeated .Request requestList = 1;</code>
     */
    proto.Hello.RequestOrBuilder getRequestListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code RequestList}
   */
  public  static final class RequestList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestList)
      RequestListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestList.newBuilder() to construct.
    private RequestList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestList() {
      requestList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                requestList_ = new java.util.ArrayList<proto.Hello.Request>();
                mutable_bitField0_ |= 0x00000001;
              }
              requestList_.add(
                  input.readMessage(proto.Hello.Request.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          requestList_ = java.util.Collections.unmodifiableList(requestList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Hello.internal_static_RequestList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Hello.internal_static_RequestList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Hello.RequestList.class, proto.Hello.RequestList.Builder.class);
    }

    public static final int REQUESTLIST_FIELD_NUMBER = 1;
    private java.util.List<proto.Hello.Request> requestList_;
    /**
     * <code>repeated .Request requestList = 1;</code>
     */
    public java.util.List<proto.Hello.Request> getRequestListList() {
      return requestList_;
    }
    /**
     * <code>repeated .Request requestList = 1;</code>
     */
    public java.util.List<? extends proto.Hello.RequestOrBuilder> 
        getRequestListOrBuilderList() {
      return requestList_;
    }
    /**
     * <code>repeated .Request requestList = 1;</code>
     */
    public int getRequestListCount() {
      return requestList_.size();
    }
    /**
     * <code>repeated .Request requestList = 1;</code>
     */
    public proto.Hello.Request getRequestList(int index) {
      return requestList_.get(index);
    }
    /**
     * <code>repeated .Request requestList = 1;</code>
     */
    public proto.Hello.RequestOrBuilder getRequestListOrBuilder(
        int index) {
      return requestList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < requestList_.size(); i++) {
        output.writeMessage(1, requestList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < requestList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, requestList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Hello.RequestList)) {
        return super.equals(obj);
      }
      proto.Hello.RequestList other = (proto.Hello.RequestList) obj;

      boolean result = true;
      result = result && getRequestListList()
          .equals(other.getRequestListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRequestListCount() > 0) {
        hash = (37 * hash) + REQUESTLIST_FIELD_NUMBER;
        hash = (53 * hash) + getRequestListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Hello.RequestList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Hello.RequestList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Hello.RequestList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Hello.RequestList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Hello.RequestList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Hello.RequestList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Hello.RequestList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Hello.RequestList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Hello.RequestList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Hello.RequestList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Hello.RequestList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Hello.RequestList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Hello.RequestList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestList)
        proto.Hello.RequestListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Hello.internal_static_RequestList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Hello.internal_static_RequestList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Hello.RequestList.class, proto.Hello.RequestList.Builder.class);
      }

      // Construct using proto.Hello.RequestList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRequestListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (requestListBuilder_ == null) {
          requestList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          requestListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Hello.internal_static_RequestList_descriptor;
      }

      public proto.Hello.RequestList getDefaultInstanceForType() {
        return proto.Hello.RequestList.getDefaultInstance();
      }

      public proto.Hello.RequestList build() {
        proto.Hello.RequestList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.Hello.RequestList buildPartial() {
        proto.Hello.RequestList result = new proto.Hello.RequestList(this);
        int from_bitField0_ = bitField0_;
        if (requestListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            requestList_ = java.util.Collections.unmodifiableList(requestList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.requestList_ = requestList_;
        } else {
          result.requestList_ = requestListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Hello.RequestList) {
          return mergeFrom((proto.Hello.RequestList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Hello.RequestList other) {
        if (other == proto.Hello.RequestList.getDefaultInstance()) return this;
        if (requestListBuilder_ == null) {
          if (!other.requestList_.isEmpty()) {
            if (requestList_.isEmpty()) {
              requestList_ = other.requestList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRequestListIsMutable();
              requestList_.addAll(other.requestList_);
            }
            onChanged();
          }
        } else {
          if (!other.requestList_.isEmpty()) {
            if (requestListBuilder_.isEmpty()) {
              requestListBuilder_.dispose();
              requestListBuilder_ = null;
              requestList_ = other.requestList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              requestListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRequestListFieldBuilder() : null;
            } else {
              requestListBuilder_.addAllMessages(other.requestList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Hello.RequestList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Hello.RequestList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.Hello.Request> requestList_ =
        java.util.Collections.emptyList();
      private void ensureRequestListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          requestList_ = new java.util.ArrayList<proto.Hello.Request>(requestList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.Hello.Request, proto.Hello.Request.Builder, proto.Hello.RequestOrBuilder> requestListBuilder_;

      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public java.util.List<proto.Hello.Request> getRequestListList() {
        if (requestListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(requestList_);
        } else {
          return requestListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public int getRequestListCount() {
        if (requestListBuilder_ == null) {
          return requestList_.size();
        } else {
          return requestListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public proto.Hello.Request getRequestList(int index) {
        if (requestListBuilder_ == null) {
          return requestList_.get(index);
        } else {
          return requestListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public Builder setRequestList(
          int index, proto.Hello.Request value) {
        if (requestListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestListIsMutable();
          requestList_.set(index, value);
          onChanged();
        } else {
          requestListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public Builder setRequestList(
          int index, proto.Hello.Request.Builder builderForValue) {
        if (requestListBuilder_ == null) {
          ensureRequestListIsMutable();
          requestList_.set(index, builderForValue.build());
          onChanged();
        } else {
          requestListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public Builder addRequestList(proto.Hello.Request value) {
        if (requestListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestListIsMutable();
          requestList_.add(value);
          onChanged();
        } else {
          requestListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public Builder addRequestList(
          int index, proto.Hello.Request value) {
        if (requestListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestListIsMutable();
          requestList_.add(index, value);
          onChanged();
        } else {
          requestListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public Builder addRequestList(
          proto.Hello.Request.Builder builderForValue) {
        if (requestListBuilder_ == null) {
          ensureRequestListIsMutable();
          requestList_.add(builderForValue.build());
          onChanged();
        } else {
          requestListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public Builder addRequestList(
          int index, proto.Hello.Request.Builder builderForValue) {
        if (requestListBuilder_ == null) {
          ensureRequestListIsMutable();
          requestList_.add(index, builderForValue.build());
          onChanged();
        } else {
          requestListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public Builder addAllRequestList(
          java.lang.Iterable<? extends proto.Hello.Request> values) {
        if (requestListBuilder_ == null) {
          ensureRequestListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, requestList_);
          onChanged();
        } else {
          requestListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public Builder clearRequestList() {
        if (requestListBuilder_ == null) {
          requestList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          requestListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public Builder removeRequestList(int index) {
        if (requestListBuilder_ == null) {
          ensureRequestListIsMutable();
          requestList_.remove(index);
          onChanged();
        } else {
          requestListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public proto.Hello.Request.Builder getRequestListBuilder(
          int index) {
        return getRequestListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public proto.Hello.RequestOrBuilder getRequestListOrBuilder(
          int index) {
        if (requestListBuilder_ == null) {
          return requestList_.get(index);  } else {
          return requestListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public java.util.List<? extends proto.Hello.RequestOrBuilder> 
           getRequestListOrBuilderList() {
        if (requestListBuilder_ != null) {
          return requestListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(requestList_);
        }
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public proto.Hello.Request.Builder addRequestListBuilder() {
        return getRequestListFieldBuilder().addBuilder(
            proto.Hello.Request.getDefaultInstance());
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public proto.Hello.Request.Builder addRequestListBuilder(
          int index) {
        return getRequestListFieldBuilder().addBuilder(
            index, proto.Hello.Request.getDefaultInstance());
      }
      /**
       * <code>repeated .Request requestList = 1;</code>
       */
      public java.util.List<proto.Hello.Request.Builder> 
           getRequestListBuilderList() {
        return getRequestListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.Hello.Request, proto.Hello.Request.Builder, proto.Hello.RequestOrBuilder> 
          getRequestListFieldBuilder() {
        if (requestListBuilder_ == null) {
          requestListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.Hello.Request, proto.Hello.Request.Builder, proto.Hello.RequestOrBuilder>(
                  requestList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          requestList_ = null;
        }
        return requestListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestList)
    }

    // @@protoc_insertion_point(class_scope:RequestList)
    private static final proto.Hello.RequestList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Hello.RequestList();
    }

    public static proto.Hello.RequestList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestList>
        PARSER = new com.google.protobuf.AbstractParser<RequestList>() {
      public RequestList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestList> getParserForType() {
      return PARSER;
    }

    public proto.Hello.RequestList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Response ResponseList = 1;</code>
     */
    java.util.List<proto.Hello.Response> 
        getResponseListList();
    /**
     * <code>repeated .Response ResponseList = 1;</code>
     */
    proto.Hello.Response getResponseList(int index);
    /**
     * <code>repeated .Response ResponseList = 1;</code>
     */
    int getResponseListCount();
    /**
     * <code>repeated .Response ResponseList = 1;</code>
     */
    java.util.List<? extends proto.Hello.ResponseOrBuilder> 
        getResponseListOrBuilderList();
    /**
     * <code>repeated .Response ResponseList = 1;</code>
     */
    proto.Hello.ResponseOrBuilder getResponseListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ResponseList}
   */
  public  static final class ResponseList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseList)
      ResponseListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseList.newBuilder() to construct.
    private ResponseList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseList() {
      responseList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                responseList_ = new java.util.ArrayList<proto.Hello.Response>();
                mutable_bitField0_ |= 0x00000001;
              }
              responseList_.add(
                  input.readMessage(proto.Hello.Response.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          responseList_ = java.util.Collections.unmodifiableList(responseList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Hello.internal_static_ResponseList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Hello.internal_static_ResponseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Hello.ResponseList.class, proto.Hello.ResponseList.Builder.class);
    }

    public static final int RESPONSELIST_FIELD_NUMBER = 1;
    private java.util.List<proto.Hello.Response> responseList_;
    /**
     * <code>repeated .Response ResponseList = 1;</code>
     */
    public java.util.List<proto.Hello.Response> getResponseListList() {
      return responseList_;
    }
    /**
     * <code>repeated .Response ResponseList = 1;</code>
     */
    public java.util.List<? extends proto.Hello.ResponseOrBuilder> 
        getResponseListOrBuilderList() {
      return responseList_;
    }
    /**
     * <code>repeated .Response ResponseList = 1;</code>
     */
    public int getResponseListCount() {
      return responseList_.size();
    }
    /**
     * <code>repeated .Response ResponseList = 1;</code>
     */
    public proto.Hello.Response getResponseList(int index) {
      return responseList_.get(index);
    }
    /**
     * <code>repeated .Response ResponseList = 1;</code>
     */
    public proto.Hello.ResponseOrBuilder getResponseListOrBuilder(
        int index) {
      return responseList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < responseList_.size(); i++) {
        output.writeMessage(1, responseList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < responseList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, responseList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Hello.ResponseList)) {
        return super.equals(obj);
      }
      proto.Hello.ResponseList other = (proto.Hello.ResponseList) obj;

      boolean result = true;
      result = result && getResponseListList()
          .equals(other.getResponseListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getResponseListCount() > 0) {
        hash = (37 * hash) + RESPONSELIST_FIELD_NUMBER;
        hash = (53 * hash) + getResponseListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Hello.ResponseList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Hello.ResponseList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Hello.ResponseList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Hello.ResponseList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Hello.ResponseList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Hello.ResponseList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Hello.ResponseList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Hello.ResponseList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Hello.ResponseList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Hello.ResponseList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Hello.ResponseList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Hello.ResponseList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Hello.ResponseList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseList)
        proto.Hello.ResponseListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Hello.internal_static_ResponseList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Hello.internal_static_ResponseList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Hello.ResponseList.class, proto.Hello.ResponseList.Builder.class);
      }

      // Construct using proto.Hello.ResponseList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResponseListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (responseListBuilder_ == null) {
          responseList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          responseListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Hello.internal_static_ResponseList_descriptor;
      }

      public proto.Hello.ResponseList getDefaultInstanceForType() {
        return proto.Hello.ResponseList.getDefaultInstance();
      }

      public proto.Hello.ResponseList build() {
        proto.Hello.ResponseList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.Hello.ResponseList buildPartial() {
        proto.Hello.ResponseList result = new proto.Hello.ResponseList(this);
        int from_bitField0_ = bitField0_;
        if (responseListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            responseList_ = java.util.Collections.unmodifiableList(responseList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.responseList_ = responseList_;
        } else {
          result.responseList_ = responseListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Hello.ResponseList) {
          return mergeFrom((proto.Hello.ResponseList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Hello.ResponseList other) {
        if (other == proto.Hello.ResponseList.getDefaultInstance()) return this;
        if (responseListBuilder_ == null) {
          if (!other.responseList_.isEmpty()) {
            if (responseList_.isEmpty()) {
              responseList_ = other.responseList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResponseListIsMutable();
              responseList_.addAll(other.responseList_);
            }
            onChanged();
          }
        } else {
          if (!other.responseList_.isEmpty()) {
            if (responseListBuilder_.isEmpty()) {
              responseListBuilder_.dispose();
              responseListBuilder_ = null;
              responseList_ = other.responseList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              responseListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResponseListFieldBuilder() : null;
            } else {
              responseListBuilder_.addAllMessages(other.responseList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Hello.ResponseList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Hello.ResponseList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.Hello.Response> responseList_ =
        java.util.Collections.emptyList();
      private void ensureResponseListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          responseList_ = new java.util.ArrayList<proto.Hello.Response>(responseList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.Hello.Response, proto.Hello.Response.Builder, proto.Hello.ResponseOrBuilder> responseListBuilder_;

      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public java.util.List<proto.Hello.Response> getResponseListList() {
        if (responseListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(responseList_);
        } else {
          return responseListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public int getResponseListCount() {
        if (responseListBuilder_ == null) {
          return responseList_.size();
        } else {
          return responseListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public proto.Hello.Response getResponseList(int index) {
        if (responseListBuilder_ == null) {
          return responseList_.get(index);
        } else {
          return responseListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public Builder setResponseList(
          int index, proto.Hello.Response value) {
        if (responseListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResponseListIsMutable();
          responseList_.set(index, value);
          onChanged();
        } else {
          responseListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public Builder setResponseList(
          int index, proto.Hello.Response.Builder builderForValue) {
        if (responseListBuilder_ == null) {
          ensureResponseListIsMutable();
          responseList_.set(index, builderForValue.build());
          onChanged();
        } else {
          responseListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public Builder addResponseList(proto.Hello.Response value) {
        if (responseListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResponseListIsMutable();
          responseList_.add(value);
          onChanged();
        } else {
          responseListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public Builder addResponseList(
          int index, proto.Hello.Response value) {
        if (responseListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResponseListIsMutable();
          responseList_.add(index, value);
          onChanged();
        } else {
          responseListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public Builder addResponseList(
          proto.Hello.Response.Builder builderForValue) {
        if (responseListBuilder_ == null) {
          ensureResponseListIsMutable();
          responseList_.add(builderForValue.build());
          onChanged();
        } else {
          responseListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public Builder addResponseList(
          int index, proto.Hello.Response.Builder builderForValue) {
        if (responseListBuilder_ == null) {
          ensureResponseListIsMutable();
          responseList_.add(index, builderForValue.build());
          onChanged();
        } else {
          responseListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public Builder addAllResponseList(
          java.lang.Iterable<? extends proto.Hello.Response> values) {
        if (responseListBuilder_ == null) {
          ensureResponseListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, responseList_);
          onChanged();
        } else {
          responseListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public Builder clearResponseList() {
        if (responseListBuilder_ == null) {
          responseList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          responseListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public Builder removeResponseList(int index) {
        if (responseListBuilder_ == null) {
          ensureResponseListIsMutable();
          responseList_.remove(index);
          onChanged();
        } else {
          responseListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public proto.Hello.Response.Builder getResponseListBuilder(
          int index) {
        return getResponseListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public proto.Hello.ResponseOrBuilder getResponseListOrBuilder(
          int index) {
        if (responseListBuilder_ == null) {
          return responseList_.get(index);  } else {
          return responseListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public java.util.List<? extends proto.Hello.ResponseOrBuilder> 
           getResponseListOrBuilderList() {
        if (responseListBuilder_ != null) {
          return responseListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(responseList_);
        }
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public proto.Hello.Response.Builder addResponseListBuilder() {
        return getResponseListFieldBuilder().addBuilder(
            proto.Hello.Response.getDefaultInstance());
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public proto.Hello.Response.Builder addResponseListBuilder(
          int index) {
        return getResponseListFieldBuilder().addBuilder(
            index, proto.Hello.Response.getDefaultInstance());
      }
      /**
       * <code>repeated .Response ResponseList = 1;</code>
       */
      public java.util.List<proto.Hello.Response.Builder> 
           getResponseListBuilderList() {
        return getResponseListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.Hello.Response, proto.Hello.Response.Builder, proto.Hello.ResponseOrBuilder> 
          getResponseListFieldBuilder() {
        if (responseListBuilder_ == null) {
          responseListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.Hello.Response, proto.Hello.Response.Builder, proto.Hello.ResponseOrBuilder>(
                  responseList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          responseList_ = null;
        }
        return responseListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseList)
    }

    // @@protoc_insertion_point(class_scope:ResponseList)
    private static final proto.Hello.ResponseList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Hello.ResponseList();
    }

    public static proto.Hello.ResponseList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseList>
        PARSER = new com.google.protobuf.AbstractParser<ResponseList>() {
      public ResponseList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseList> getParserForType() {
      return PARSER;
    }

    public proto.Hello.ResponseList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/hello.proto\"#\n\007Request\022\n\n\002id\030\001 \001" +
      "(\003\022\014\n\004name\030\002 \001(\t\"$\n\010Response\022\n\n\002id\030\001 \001(\003" +
      "\022\014\n\004name\030\002 \001(\t\",\n\013RequestList\022\035\n\013request" +
      "List\030\001 \003(\0132\010.Request\"/\n\014ResponseList\022\037\n\014" +
      "ResponseList\030\001 \003(\0132\t.ResponseB\007\n\005protob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_RequestList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RequestList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestList_descriptor,
        new java.lang.String[] { "RequestList", });
    internal_static_ResponseList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseList_descriptor,
        new java.lang.String[] { "ResponseList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
