/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class meta_HelloMetaCpp */

#ifndef _Included_meta_HelloMetaCpp
#define _Included_meta_HelloMetaCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     meta_HelloMetaCpp
 * Method:    hello
 * Signature: (Lmeta/Request;)Lmeta/Response;
 */
JNIEXPORT jobject JNICALL Java_meta_HelloMetaCpp_hello
  (JNIEnv *, jobject, jobject);

/*
 * Class:     meta_HelloMetaCpp
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_meta_HelloMetaCpp_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     meta_HelloMetaCpp
 * Method:    toString
 * Signature: (Ljava/lang/Integer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_meta_HelloMetaCpp_toString
  (JNIEnv *, jobject, jobject);

/*
 * Class:     meta_HelloMetaCpp
 * Method:    toInt
 * Signature: (Ljava/lang/String;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_meta_HelloMetaCpp_toInt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
