/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class proto_HelloProto */

#ifndef _Included_proto_HelloProto
#define _Included_proto_HelloProto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     proto_HelloProto
 * Method:    hello
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_proto_HelloProto_hello
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     proto_HelloProto
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_proto_HelloProto_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
