/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class callback_CallbackJNI */

#ifndef _Included_callback_CallbackJNI
#define _Included_callback_CallbackJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     callback_CallbackJNI
 * Method:    setCallback
 * Signature: (Lcallback/MyCallback;)V
 */
JNIEXPORT void JNICALL Java_callback_CallbackJNI_setCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     callback_CallbackJNI
 * Method:    handle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_callback_CallbackJNI_handle
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
